P5/Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using The_Car_Hub.Models;
using The_Car_Hub.Models.Services;

namespace The_Car_Hub.Controllers
{
    public class CarController : Controller
    {
        private readonly IInventoryService _inventoryService;
        private readonly IConfiguration _configuration;
        public InventoryViewModel InventoryViewModel { get; private set; }

        public CarController(IInventoryService inventoryService,IConfiguration configuration)
        {
            _inventoryService = inventoryService;
            _configuration = configuration;
        }

        public async Task<IActionResult> Index()
        {
            List<InventoryViewModel> model = await _inventoryService.GetAllInventoryAsync();
            return View(model);
        }

        public async Task<IActionResult> Details(int id)
        {
            var InventoryViewModel = await _inventoryService.MapInventoryViewModelAsync(id);

            ViewBag.Name = _configuration.GetSection("Contact").GetSection("Name").Value;
            ViewBag.Phone = _configuration.GetSection("Contact").GetSection("Phone").Value;
            ViewBag.MobilePhone = _configuration.GetSection("Contact").GetSection("Mobile phone").Value;
            ViewBag.Email = _configuration.GetSection("Contact").GetSection("Email").Value;

            if (InventoryViewModel == null)
            {
                Response.StatusCode = 404;
                throw new Exception("No Car found");
            }

            return View(InventoryViewModel);
        }

        public async Task<IActionResult> Listing()
        {
            List<InventoryViewModel> model = await _inventoryService.GetAllInventoryAsync();

            return View(model);
        }

        public IActionResult Contact()
        {
            return View();
        }
    }
}

P5/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using The_Car_Hub.Helper;
using The_Car_Hub.Models;
using The_Car_Hub.Models.Services;

namespace The_Car_Hub.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly IInventoryService _inventoryService;
        private readonly IWebHostEnvironment _hostEnvironment;

        public DashboardController(IInventoryService inventoryService,IWebHostEnvironment hostEnvironment)
        {
            _inventoryService = inventoryService;
            _hostEnvironment = hostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            List<InventoryViewModel> model = await _inventoryService.GetAllInventoryAsync();
            ViewBag.UnusedImages = CountUnusedImage();

            return View(model);
        }

        public async Task<IActionResult> AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View();
            else
            {
                var inventoryViewModel = await _inventoryService.MapInventoryViewModelAsync(id);

                if (inventoryViewModel == null)
                {
                    return NotFound();
                }

                return View(inventoryViewModel);
            }
        }

        [AcceptVerbs("Get","Post")]
        public async Task<IActionResult> VerifyVIN(string VIN)
        {
            if (!string.IsNullOrEmpty(VIN))
            {
                var result = await _inventoryService.VerifyVIN(VIN);
                return Json(result ? "true" : string.Format("VIN : {0} already exists.",VIN));
            }

            return Json("false");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(int id,InventoryViewModel inventoryViewModel)
        {
            if (ModelState.IsValid)
            {
                //Insert
                if (id == 0)
                {
                    await _inventoryService.SaveInventory(inventoryViewModel);
                    ViewBag.SuccessMsg = "Successfully added";
                }
                //Update
                else
                {
                    try
                    {
                        await _inventoryService.UpdateInventory(inventoryViewModel);
                        ViewBag.SuccessMsg = "Successfully edited";
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        throw;
                    }
                }
                return Json(new { isValid = true,html = RazorHelper.RenderRazorViewToString(this,"_ViewAll",await _inventoryService.GetAllInventoryAsync()),Count = CountUnusedImage() });
            }

            return Json(new { isValid = false,html = RazorHelper.RenderRazorViewToString(this,"AddOrEdit",inventoryViewModel),Count = CountUnusedImage() });
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await _inventoryService.DeleteInventory((int)id);
            ViewBag.SuccessMsg = $"Id : {id} Successfully deleted";

            return Json(new { isValid = true,html = RazorHelper.RenderRazorViewToString(this,"_ViewAll",await _inventoryService.GetAllInventoryAsync()),Count = CountUnusedImage() });
        }

        public async Task<IActionResult> DeleteAll()
        {
            await _inventoryService.DeleteAll();
            ViewBag.SuccessMsg = "All cars successfully deleted";

            return Json(new { isValid = true,html = RazorHelper.RenderRazorViewToString(this,"_ViewAll",await _inventoryService.GetAllInventoryAsync()),Count = CountUnusedImage() });
        }

        public async Task<IActionResult> EmptyImageFolder()
        {
            await _inventoryService.DeleteUnusedImage();
            ViewBag.SuccessMsg = "All images successfully deleted";

            return Json(new { isValid = true,html = RazorHelper.RenderRazorViewToString(this,"_ViewAll",await _inventoryService.GetAllInventoryAsync()),Count = CountUnusedImage() });
        }

        public async Task<int> CountUnusedImage()
        {
            var filesPath = await _inventoryService.GetUnusedImage();

            return filesPath.Count();
        }

        public async Task<IActionResult> Export()
        {
            string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            string fileName = "data.xlsx";

            var content = await _inventoryService.Export();
            ViewBag.SuccessMsg = "Successfully exported";

            return File(content,contentType,fileName);
        }
    }
}

P5/Views/Dashboard/Index.cshtml
@model IEnumerable<The_Car_Hub.Models.InventoryViewModel>

@{
    ViewBag.Title = "The Car Hub - Dashboard";
    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml";

}
<div id="view-all">
    @await Html.PartialAsync("_ViewAll",Model)
</div>

P5/Views/Dashboard/_ViewAll.cshtml
@model IEnumerable<The_Car_Hub.Models.InventoryViewModel>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Collapsable</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                </div>
                <!-- /.card-tools -->
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-3 col-3 col-sm1">
                        <!-- small box -->
                        <div class="small-box bg-primary">
                            <div class="inner">
                                <h3>@Model.Count()</h3>

                                <p>Cars</p>
                            </div>
                            <div class="icon">
                                <i class="fas fa-download"></i>
                            </div>
                            <a class="small-box-footer" asp-action="Export">Export <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-3 col-sm1">
                        <!-- small box -->
                        <div class="small-box bg-danger">
                            <div class="inner">
                                <h3>@Model.Count()</h3>

                                <p>Delete All Cars</p>
                            </div>
                            <div class="icon">
                                <i class="fas fa-car"></i>
                            </div>
                            <a class="small-box-footer" onclick="jQueryAjaxDeleteAll()">Delete <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-3 col-sm1">
                        <!-- small box -->
                        <div class="small-box bg-success">
                            <div class="inner">
                                @if (ViewBag.UnusedImages?.Result != null)
                                {
                                    <h3 id="unusedImages">@ViewBag.UnusedImages.Result</h3>
                                }
                                else
                                {
                                    <h3 id="unusedImages">0</h3>
                                }
                                <p>Unused images</p>
                            </div>
                            <div class="icon">
                                <i class="fas fa-car"></i>
                            </div>
                            @if (ViewBag.UnusedImages?.Result == 0)
                            {
                                <a class="small-box-footer" style="pointer-events: none !important;">Empty space <i class="fas fa-arrow-circle-right"></i></a>
                            }
                            else
                            {
                                <a class="small-box-footer" asp-action="EmptyImageFolder">Empty space <i class="fas fa-arrow-circle-right"></i></a>
                            }
                        </div>
                    </div>
                    <div class="col-lg-3 col-3 col-sm1">
                        <div class="card bg-warning text-white">
                            <div class="card-header">
                                <h3 class="card-title">Automatic fees $</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <input id="feeValue" type="number" value="500" min="0" max="5000" step="50" />
                                <script>
                                    $("input[type='number']").inputSpinner();
                                </script>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Inventory Card Text</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table id="inventoryTable" class="table table-striped table-bordered table-hover table-sm">
                    <thead class="thead-dark">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.VIN)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Make)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Model)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PurchaseDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PurchasePrice)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LotDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.SaleDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Year)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Color)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Status)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <a target="_blank" rel="noopener noreferrer" href="@Url.Action("Details","Car",new {id=item.Id},Context.Request.Scheme)">@Html.DisplayFor(modelItem => item.VIN)</a>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Make)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Model)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PurchaseDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PurchasePrice)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LotDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SaleDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Year)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Color)
                                </td>
                                <td>
                                    @switch (item.Status)
                                    {
                                        case "Unavaible":
                                            <span class="badge badge-danger">
                                                @Html.DisplayFor(modelItem => item.Status)
                                            </span>
                                            break;
                                        case "Maintenance":
                                            <span class="badge badge-warning">
                                                @Html.DisplayFor(modelItem => item.Status)
                                            </span>
                                            break;
                                        case "OnSale":
                                            item.Status = "On sale";
                                            <span class="badge badge-primary">
                                                @Html.DisplayFor(modelItem => item.Status)
                                            </span>
                                            break;
                                        case "Sold":
                                            <span class="badge badge-success">
                                                @Html.DisplayFor(modelItem => item.Status)
                                            </span>
                                            break;
                                        default:
                                            break;
                                    }
                                </td>
                                <td>
                                    <div>

                                        <a onclick="showInPopup('@Url.Action("AddOrEdit","Dashboard",new {id=item.Id},Context.Request.Scheme)','Update Inventory')" class="btn btn-info text-white"><i class="fas fa-pencil-alt"></i> Edit</a>
                                        <form asp-action="Delete" asp-route-id="@item.Id" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
                                            <input type="submit" value="Delete" class="btn btn-danger" />
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
</div>
<p>
    <a onclick="showInPopup('@Url.Action("AddOrEdit","Dashboard",null,Context.Request.Scheme)','Create')" class="btn btn-success text-white">Create New</a>
</p>
<!-- /.row -->
<script>
    $(function () {
        $('#inventoryTable').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
        })
    })

    var message = '@ViewBag.SuccessMsg'

    if(message){
        FireToast(message)
    }
</script>